import streamlit as st
import pandas as pd
from pathlib import Path


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AI Vision Intelligence",
    page_icon="🖐️",
    layout="wide"
)


# ============================================================
# PROJECT PATH
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

LOG_PATH = PROJECT_ROOT / "logs" / "predictions.csv"


# ============================================================
# TITLE
# ============================================================

st.title("🖐️ AI Vision Intelligence System")

st.subheader("Real-Time Hand Gesture Analytics")


# ============================================================
# CHECK LOG FILE
# ============================================================

if not LOG_PATH.exists():

    st.warning("Prediction log file not found.")

    st.stop()


# ============================================================
# LOAD DATA
# ============================================================

df = pd.read_csv(LOG_PATH)


# ============================================================
# CHECK DATA
# ============================================================

if df.empty:

    st.info("No predictions have been logged yet.")

    st.stop()


# ============================================================
# CLEAN DATA
# ============================================================

df["confidence"] = pd.to_numeric(
    df["confidence"],
    errors="coerce"
)

df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)


# ============================================================
# DASHBOARD METRICS
# ============================================================

total_predictions = len(df)

average_confidence = df["confidence"].mean()

most_common_gesture = (
    df["gesture"].mode()[0]
    if not df["gesture"].mode().empty
    else "N/A"
)

latest_gesture = df.iloc[-1]["gesture"]


# ============================================================
# METRIC CARDS
# ============================================================

col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(
        "Total Predictions",
        total_predictions
    )


with col2:

    st.metric(
        "Average Confidence",
        f"{average_confidence:.1f}%"
    )


with col3:

    st.metric(
        "Most Detected Gesture",
        most_common_gesture
    )


with col4:

    st.metric(
        "Latest Gesture",
        latest_gesture
    )


# ============================================================
# GESTURE DISTRIBUTION
# ============================================================

st.subheader("📊 Gesture Distribution")

gesture_counts = (
    df["gesture"]
    .value_counts()
)

st.bar_chart(gesture_counts)


# ============================================================
# CONFIDENCE ANALYSIS
# ============================================================

st.subheader("🎯 Confidence Analysis")

st.line_chart(
    df["confidence"]
)


# ============================================================
# RECENT PREDICTIONS
# ============================================================

st.subheader("🕒 Recent Predictions")

recent_data = df.tail(20).iloc[::-1]

st.dataframe(
    recent_data,
    use_container_width=True
)


# ============================================================
# PROJECT INFORMATION
# ============================================================

st.subheader("ℹ️ Project Information")

st.write(
    """
    This dashboard displays real-time hand gesture predictions
    generated by the AI Vision Intelligence System.

    The system uses MediaPipe for hand landmark detection
    and a Random Forest machine learning model for gesture
    classification.
    """
)